name: Test Bot

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify files
        run: |
          cd py  # Переходим в папку py
          ls -la
          [ -f db.py ] || { echo "db.py not found!"; exit 1; }
          echo "All files present!"
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          cd py
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test DB initialization
        run: |
          cd py
          python -c "from db import init_db; init_db(); print('Database initialized successfully')"
          
      - name: Verify imports
        run: |
          cd py
          python -c "from config import TOKEN, ADMIN_ID; from bot import main; print('All imports work')"
